name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.1.0

    - name: Change permissions of Gradle wrapper script
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Install Allure
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure

    - name: Generate Allure Report
      run: ./gradlew allureReport

    - name: Upload Allure results
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: build/allure-results

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: build/reports/allure-report

  dependency-submission:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/gradle-dependency-submission-action@v3.1.0
